name: CI

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install OS deps
        run: ./tools/deps/os/ubuntu.sh
      - name: Run CI
        run: make ci
